In [8]:
import numpy as np

x = a = np.arange(24).reshape((2,3,4))
print(x)
print()

y = x.reshape((6,-1))
print(y.shape)
print(y)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

(6, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [2]:
if 1==1: print('hi'), print('no')

hi
no
